version: '3.8'

services:
  books-db: # Configuration for the database service.
    image: postgis/postgis:13-3.1  
    volumes: 
      - postgres_data:/var/lib/postgresql/data/  # Maps a volume for PostgresSQL data storage.
    env_file:
      - ./.env 
    networks: 
      - books_api_network  

  books-redis: # Configuration for the Redis service.
    image: "redis:7.2.1"  
    env_file: 
      - ./.env  
    command: redis-server --requirepass ${REDIS_PASSWORD-8600966989}
    networks: 
      - books_api_network

volumes: # Defines named volumes for persistent storage.
  postgres_data:  # Defines a named volume for PostgresSQL data storage.

networks: 
  books_api_network:  # Configuration for the "books_api_network" network.
    external: true  # Indicates that this network is defined externally and should be reused if it already exists.